name: Trigger assets repo

on:
  push:
    branches:
      - master
    paths:
      - services/bot/*
      - .github/workflows/pandora-with-assets.yml

jobs:
  build-push-pandora:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: cq-pandora
        repo: assets
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow_file_name: build-docker-images.yml
        wait_workflow: false
