name: Trigger assets repo

on:
  push:
    branches:
      - master
    paths:
      - services/bot/*
      - .github/workflows/pandora-with-assets.yml

jobs:
  build-push-pandora:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait
      with:
        owner: cq-pandora
        repo: assets
        github_user: ${{ secrets.PERSONAL_ACCESS_TOKEN_OWNER }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        workflow_file_name: build-docker-images.yml
        wait_workflow: false
        ref: master
